---
# tasks file for ucsdlib.redis

- name: Get per OS Family Package Name
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install Redis
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ redis_packages }}'

- name: Enable Redis
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - '{{ redis_packages }}'
